// argsea · shared site data
// Single source of truth for the light list. Loaded via <script src="./site-data.js">
// in each page's helmet; pages read window.ARGSEA_DATA.
// In production this is the JSON the admin ("the keeper's office") serves.
// Case studies are markdown in the keeper's dialect:
//   ## heading            -> numbered section
//   plain paragraphs      -> prose
//   > line                -> "from the log" aside
//   - item                -> list
//   [? fact needed ?]     -> amber placeholder chip (facts only the keeper knows)
//   ![caption](key)       -> figure for picture <key>, caption beneath.
//                            pictures are managed per project in the admin's "pictures" gallery
//                            (slot id proj-<slug>-img-<key>); the FIRST picture in `images` is the
//                            entry photo shown on the flagship polaroid and in the entry overlay.
//   :::facts ... :::      -> label: value rows, rendered as a fact grid
//   :::outcomes ... :::   -> "big | caption" lines, rendered as outcome cards
//   ```mermaid ... ```    -> diagram, themed to the site palette
// Provenance: assist: { harness, model } on a project means keeper + AI together
// (Me + AI stamps); add only: true for AI-built-solo (AI stamp alone); absent
// means lit by hand (Me stamp alone). Pages render all three states.
window.ARGSEA_DATA = {
  // the keeper's journal · single source; Notes and Hello render it, the light
  // overlay reads a note out of the tower's log (project.notes ties by title)
  journal: [
    { date: 'jun 2026', title: 'What re-architecting taught me about not architecting',
      wx: 'light steady · no incidents', doodle: 'diagram', doodleCaption: 'the new system, not built',
      teaser: 'Sometimes the best system design is the meeting where you talk everyone out of a new system.',
      p1: 'The most valuable architecture work I did last year produced zero diagrams. It was a meeting where we decided not to build a new system, because the old one was fine and the problem was actually a missing index.',
      p2: 'Nobody frames that. There is no conference talk called "We Kept The Thing." But keeping the thing, understanding it well enough to defend it, is harder than replacing it, and pays better.',
      p3: 'So my current architecture checklist starts with one question: what if we did nothing? It is amazing how often "nothing" is a strong candidate.' },
    { date: 'apr 2026', title: 'CachyOS, three months in', doodle: 'boat', doodleCaption: 'the next distro, on the horizon',
      wx: 'fog inland · desktop suspiciously calm',
      teaser: 'A review from someone who will absolutely distro-hop again and lie about it.',
      p1: 'Three months on CachyOS and everything works, which is deeply unsettling. A Linux desktop is supposed to be a relationship with problems. This one just... boots.',
      p2: 'I have compensated by inventing problems: kernel flavors, shader pre-caching, a systemd unit that exists purely because I wanted to write one.',
      p3: 'Verdict: excellent. Will I still be here next year? History says no. History also says I will claim the next distro is "finally the one," so take this note as a hostage statement.' },
    { date: 'feb 2026', title: 'The queue is the product',
      wx: 'wind NW · queue quiet', doodle: 'queue', doodleCaption: 'the product.',
      teaser: 'Notes on message queues after a decade of them quietly running the news.',
      p1: 'A decade of publishing systems has convinced me the real product is not the website or the app. It is the queue: the quiet agreement about what happens next, in what order, and what happens when it fails.',
      p2: 'Every incident postmortem I have ever written eventually finds a place where two systems disagreed about that. Every fix eventually looks like a queue wearing a disguise.',
      p3: 'If you can only design one thing well, design the handoff. The rest is UI.' },
  ],
  // the wandering chart · hobbies, past and adrift (Hobbies renders these).
  // a hobby's `notes` ties it to journal entries by title, same as a project's `notes`;
  // Notes links back to the chart via Hobbies.dc.html?bearing=<name>.
  // gauge: enthusiasm, self-assessed, suspiciously precise. Homepage bars only.
  hobbies: [
    { name: 'The home lab', gauge: 94, service: '2021 · present', state: 'moored', coord: { lat: 58.22, lon: -7.50 }, seasons: '5', notes: ['CachyOS, three months in'],
      bearing: 'Moored in the lee of Eilean Mòr, in sight of the keepers’ light. Never left the harbor.',
      lastLog: '"All lamps green. One tweak from perfect. Will fix tonight." · every log entry, verbatim, since 2021.',
      offCourse: 'It never went off course. It is moored where I can watch it from the lamp room.',
      floats: 'everything. that is the whole point.',
      odds: 'in port indefinitely' },
    { name: 'Piano', gauge: 38, service: '2023 · 2024', state: 'adrift', coord: { lat: 58.42, lon: -7.12 }, from: { lat: 58.24, lon: -7.44 }, seasons: '2',
      bearing: 'Last seen drifting off the north point, sails slack, no hand at the tiller.',
      lastLog: '"Got through the piece with both hands tonight. Good enough." · final entry, unsigned.',
      offCourse: 'Slipped its mooring the night it was "good enough" and drifted out on the tide.',
      floats: 'one shaky recording the family still requests',
      odds: 'likely · pending a child\u2019s curiosity' },
    { name: 'Music theory', gauge: 51, service: '2023 · 2024', state: 'marooned', coord: { lat: 58.06, lon: -7.20 }, from: { lat: 58.28, lon: -7.30 }, seasons: '2',
      bearing: 'Marooned on a small isle, the same sandbar the piano washed up on.',
      lastLog: '"The circle of fifths is just modular arithmetic wearing a cape." · margin note, underlined twice.',
      offCourse: 'Went overboard the same night as piano; the two washed up together.',
      floats: 'annotated chord charts, still in a drawer',
      odds: 'rises with every tide the piano does' },
    { name: 'Game dev', gauge: 88, service: '2020', state: 'port', coord: { lat: 58.20, lon: -6.75 }, from: { lat: 58.02, lon: -6.60 }, seasons: '1',
      bearing: 'Moored in a safe harbor, colors still flying. Came in on purpose.',
      lastLog: '"Shipped. The cat is the boat. No further business." · last entry, signed with a flourish.',
      offCourse: 'Reached port, dropped anchor by choice, and ran the pennants up.',
      floats: 'Meo Wave Race, complete and undefeated · see light no. 008',
      odds: 'slim · the logbook is already perfect' },
    { name: 'Running', gauge: 12, service: 'one summer', state: 'inkspill', coord: { lat: 57.92, lon: -7.02 }, from: { lat: 58.06, lon: -7.10 }, seasons: '\u00bc',
      bearing: 'Coordinates smudged. An ink-well tipped across this one and never dried.',
      lastLog: '"5k tomorrow, then every morning after." · only entry.',
      offCourse: 'An ink-well tipped over the chart and blotted the bearing to an unreadable smudge.',
      floats: 'the shoes. the shoes remain.',
      odds: 'spring keeps promising a fair wind' },
  ],
  projects: [
    { title: 'The Great Un-monolithing', cat: 'backend', color: 'white', kind: 'flash', period: 8, est: '2024', status: 'lit', flagship: true,
      desc: 'One giant app became many small, well-behaved services. Readers never noticed. That was the point.',
      tags: ['kubernetes', 'python', 'rabbitmq'],
      images: ['first-screenshot'],
      facts: [
        { k: 'ownership', v: 'design to operations, solo' },
        { k: 'scale', v: '29 services · ~2M visits a month' },
        { k: 'constraint', v: 'the paper came out every day, mid-migration' },
        { k: 'result', v: 'the old stack went dark in 2025' },
      ],
      notes: ['What re-architecting taught me about not architecting', 'The queue is the product'],
      details1: 'The old system was one enormous application that did everything and feared nothing, least of all my weekends. I took it apart piece by piece: a message queue in the middle, 29 services around it, Kubernetes herding the containers.',
      details2: 'The success metric was silence. No reader ever noticed a thing. The paper published every single day while I swapped the engine mid-flight.',
      moral: 'Moral: the best migrations are the boring ones.',
      to: 'everyone who reads the news without thinking about queues', from: 'justin, from inside the cluster', year: '2024 - ongoing',
      caseStudy: [
        '## The starting point',
        '',
        'The Post-Gazette\'s publishing stack had been accreting since roughly 2016. One enormous application that did everything and feared nothing, least of all my weekends. Deploys were [? how deploys worked, and how scary ?], and every change carried the whole system\'s risk.',
        '',
        'The constraints were plain. One engineer. Bare metal on premises, no cloud autoscaling to hide behind. And a paper that publishes every single day, so there was no maintenance window big enough to swap the stack in one move.',
        '',
        '> Drew the boxes before the arrows. Always the boxes first.',
        '',
        '## The shape of it',
        '',
        'Services stay small, own their data, and talk through RabbitMQ instead of calling each other directly. Varnish absorbs read traffic at the edge, so a couple million visits a month never becomes a couple million origin hits. MetalLB hands out real IPs, because bare metal does not come with a load balancer.',
        '',
        '```mermaid',
        'flowchart TB',
        '  lb[metallb] --> ing[nginx ingress]',
        '  ing --> va[varnish cache]',
        '  va --> bus{{rabbitmq · the event bus}}',
        '  bus --> svc[python services · x29]',
        '  svc --> mdb[(mongodb)]',
        '  svc --> rds[(redis)]',
        '```',
        '',
        'The rule that made 29 services survivable for one keeper: every service looks the same. Same repo layout, same base image, same health checks, same way onto and off the bus. The novelty budget goes to the problem, not the plumbing.',
        '',
        '## Migrating while the paper ships',
        '',
        'The monolith came apart one capability at a time. Peel a function off, stand it up as a service on the bus, route traffic to it, watch it for a while, then delete the old code path. Repeat 29 times. The first peel was [? the first service extracted, and why it went first ?].',
        '',
        'Order mattered more than speed. Low-risk, high-annoyance pieces went first, to prove the pattern. The scary ones went last, once the platform had earned trust.',
        '',
        ':::facts',
        'timeline: [? months to production, months refining ?]',
        'first peel: [? service name ?]',
        'scariest peel: [? service name, and why it waited ?]',
        ':::',
        '',
        '## What went wrong',
        '',
        '> The lamp swap happened at night. Obviously.',
        '',
        'Events everywhere is worth it for the decoupling, and you pay for it in debugging: tracing a story across queues is harder than reading a stack trace. [? how you trace across the bus today ?]',
        '',
        '![the first screenshot, from the station archive](first-screenshot)',
        '',
        'The mistake worth admitting: [? the thing that actually broke once, and what it taught you ?]',
        '',
        '## What I\'d change now',
        '',
        '- Fewer, fatter services from day one. The honest number is probably [? your honest number ?].',
        '- [? the second thing you\'d do differently ?]',
        '- [? the opinion only someone who ran this would have ?]',
        '',
        '## Outcomes',
        '',
        ':::outcomes',
        '29 services | in production, uniform, one keeper',
        '~2M visits/mo | served through the platform',
        '0 missed papers | it published every day, the whole way through',
        'old stack: dark | decommissioned 2025 · see light no. 014',
        ':::',
      ].join('\n') },
    { title: 'Newsroom plumbing', cat: 'backend', color: 'white', kind: 'fixed', period: 0, est: '2016', status: 'lit',
      desc: 'A publishing workflow a real paper runs on, every day, deadlines and all.',
      tags: ['rest', 'mongodb', 'nginx'],
      images: ['station-photo'],
      facts: [
        { k: 'role', v: 'APIs, storage, caching · design and build' },
        { k: 'tenure', v: 'core plumbing since 2016' },
        { k: 'constraint', v: 'deadlines that do not move for anybody' },
        { k: 'result', v: 'nobody knows it exists. that is the review.' },
      ],
      details1: "Reporters write, editors edit, and somewhere between 'done' and 'published' lives an entire hidden city of pipes. I designed and built a good chunk of that city: APIs, storage, caching, the works.",
      details2: 'It runs on deadlines that do not move for anybody. The plumbing holds. Mostly nobody knows it exists, which is exactly how plumbing should work.',
      moral: 'Moral: a fixed light never blinks. It just holds.',
      to: 'the 6pm deadline', from: 'the pipes beneath the newsroom', year: '2016 - ongoing' },
    { title: '100k good mornings', cat: 'backend', color: 'white', kind: 'occult', period: 6, est: '2018', status: 'lit',
      desc: 'An automated newsletter that beats the sunrise into six figures of inboxes.',
      tags: ['php', 'redis', 'linux'],
      facts: [
        { k: 'audience', v: '100,000+ inboxes, every morning' },
        { k: 'schedule', v: 'assembled and delivered before sunrise' },
        { k: 'design goal', v: 'boring on purpose: retries, queues, monitoring' },
        { k: 'reliability', v: 'better attendance than the keeper' },
      ],
      details1: 'Every morning, before coffee exists, an automated system assembles the day\u2019s news and delivers it to over 100,000 inboxes. It has done this more reliably than I get out of bed.',
      details2: 'The fun part was making it boring: retries, queues, monitoring, and a healthy paranoia about what happens at 4am when nobody is watching.',
      moral: 'Moral: automation is just kindness to your future self, scheduled.',
      to: '100,000 people who are not awake yet', from: 'a cron job with ambition', year: '2018 - ongoing' },
    { title: 'Meo Wave Race', cat: 'games', color: 'green', kind: 'flash', period: 4, est: '2020', status: 'dark', disco: '2020',
      desc: 'A cat/boat racing game for the CS50 final. The cat is the boat. Lit once, brilliantly, then retired.',
      tags: ['unity', 'c#', 'blender'],
      facts: [
        { k: 'made for', v: 'the CS50 final' },
        { k: 'scope', v: 'modeling, shaders, physics · one person' },
        { k: 'review panel', v: 'two children · 10/10' },
        { k: 'record', v: 'retired undefeated' },
      ],
      details1: 'For the CS50 final I made a racing game where a cat is also a boat. I modeled the cat. I modeled the waves. I wrote shaders. I regret nothing.',
      details2: 'It shipped, it ran, and then I put out the light on purpose. One game made, one game finished, undefeated. A light discontinued at its peak is still a light that worked.',
      moral: 'Moral: retire at the top.' },
    { title: 'This website', cat: 'this website', color: 'white', kind: 'iso', period: 3, est: '2026', status: 'lit',
      desc: "The light you're standing in. Its characteristic changes without notice, by order of the keeper.",
      tags: ['meta', 'html', 'whimsy'],
      assist: { harness: 'Claude Code', model: 'Opus 4.8' },
      facts: [
        { k: 'version', v: 'v2 of n, n unbounded' },
        { k: 'stack', v: 'html, css, one lighthouse' },
        { k: 'uptime', v: 'the light runs on a schedule. ish.' },
        { k: 'risk', v: 'total rebuild whenever the mood strikes' },
      ],
      details1: 'You are here. Previous versions had a space theme and a particle system that heated homes across Pittsburgh. This one has a lighthouse, a hobby graveyard, and a light list.',
      details2: 'It gets rebuilt whenever the mood strikes, which historically is often. Consider this entry accurate until roughly the moment you finish reading it.',
      moral: 'Moral: the portfolio is also the hobby.' },
    { title: 'The home lab', cat: 'tinkering', color: 'red', kind: 'fixed', period: 0, est: '2021', status: 'lit',
      desc: 'Plex, HTPC, and a small fleet of machines that mostly behave. The red light that stays on at home.',
      tags: ['plex', 'linux', 'cachyos'],
      facts: [
        { k: 'fleet', v: 'plex server, htpc, desktop, stragglers' },
        { k: 'status', v: 'one tweak from perfect, forever' },
        { k: 'audience', v: 'the family, mostly for the movies' },
        { k: 'budget', v: 'do not ask' },
      ],
      details1: 'A Plex server, an HTPC, CachyOS on the desktop, and a small fleet of machines that mostly behave. This is the one hobby that survives every purge, because it is just the day job wearing pajamas.',
      details2: 'Current status, as always: one tweak from perfect. The tweak changes weekly. Perfect remains at a fixed distance, like the horizon.',
      moral: 'Moral: some lights you keep burning just for the family.' },
    { title: 'The old publishing stack', cat: 'backend', color: 'white', kind: 'fixed', period: 0, est: '2016', status: 'dark', disco: '2025',
      desc: 'A lot, that did very little. Put out by light no. 002, one piece at a time.',
      tags: ['monolith', 'legacy'],
      facts: [
        { k: 'era', v: '2016 to 2025' },
        { k: 'scope', v: 'a lot, that did very little' },
        { k: 'fate', v: 'decommissioned by no. 002, piece by piece' },
        { k: 'legacy', v: 'every light on this coast' },
      ],
      details1: 'The monolith itself deserves an honest entry: it ran a real newspaper for the better part of a decade, and it never asked permission to page me. Every system on this coast exists because this one existed first.',
      details2: 'It was decommissioned in 2025, capability by capability, until one night there was nothing left to turn off. No wake. The queue drained, the DNS flipped, and the coast got quieter.',
      moral: 'Moral: a good platform is measured by what it lets you turn off.' },
  ],
};
